version: '3.0'
services:
  host-app:
    build:
      context: ./host_app
    ports:
      - "9000:9000"
    container_name: host-app-gestor
    stdin_open: true
    tty: true
  navbar:
    build:
      context: ./navbar
    ports:
      - "9002:80"
    container_name: navbar-gestor
    stdin_open: true
    tty: true
  styleguide:
    build:
      context: './styleguide'
    ports:
      - "9003:80"
    container_name: styleguide-gestor
    stdin_open: true
    tty: true
  visualizador-calidad-aire:
    build:
      context: './visualizador_calidad_aire'
    ports:
      - "9006:80"
    container_name: visualizador-calidad-aire-gestor
    stdin_open: true
    tty: true
  visualizador-restriccion:
    build:
      context: './visualizador_restriccion'
    ports:
      - "9007:80"
    container_name: visualizador-restriccion-gestor
    stdin_open: true
    tty: true
  turismo:
    build:
      context: './turismo'
    ports:
      - "9008:80"
    container_name: turismo-gestor
    stdin_open: true
    tty: true
  ambientes-cerrados:
    build:
      context: './ambientes_cerrados'
    ports:
      - "9009:80"
    container_name: ambientes-cerrados-gestor
    stdin_open: true
    tty: true
  ambientes-abiertos:
    build:
      context: './ambientes_abiertos'
    ports:
      - "9010:80"
    container_name: ambientes-abiertos-gestor
    stdin_open: true
    tty: true
  deportes:
    build:
      context: './deportes'
    ports:
      - "9011:80"
    container_name: deportes-gestor
    stdin_open: true
    tty: true
  entretenimiento:
    build:
      context: './entretenimiento'
    ports:
      - "9012:80"
    container_name: entretenimiento-gestor
    stdin_open: true
    tty: true
  entretenimiento-familiar:
    build:
      context: './entretenimiento_familiar'
    ports:
      - "9013:80"
    container_name: entretenimiento-familiar-gestor
    stdin_open: true
    tty: true
  entretenimiento-tercera-edad:
    build:
      context: './entretenimiento_tercera_edad'
    ports:
      - "9014:80"
    container_name: entretenimiento-tercera-edad-gestor
    stdin_open: true
    tty: true
  entretenimiento-adulto:
    build:
      context: './entretenimiento_adulto'
    ports:
      - "9015:80"
    container_name: entretenimiento-adulto-gestor
    stdin_open: true
    tty: true