version: '3.0'
services:
  host_app:
    build:
      context: ./host_app
    ports:
      - "80:80"
    container_name: host_app_gestor
    stdin_open: true
    tty: true
  navbar:
    build:
      context: ./navbar
    ports:
      - "9002:80"
    container_name: navbar_gestor
    stdin_open: true
    tty: true
  styleguide:
    build:
      context: './styleguide'
    ports:
      - "9003:80"
    container_name: styleguide_gestor
    stdin_open: true
    tty: true
  visualizador_calidad_aire:
    build:
      context: './visualizador_calidad_aire'
    ports:
      - "9006:80"
    container_name: visualizador_calidad_aire_gestor
    stdin_open: true
    tty: true
  visualizador_restriccion:
    build:
      context: './visualizador_restriccion'
    ports:
      - "9007:80"
    container_name: visualizador_restriccion_gestor
    stdin_open: true
    tty: true
  turismo:
    build:
      context: './turismo'
    ports:
      - "9008:80"
    container_name: turismo_gestor
    stdin_open: true
    tty: true
  ambientes_cerrados:
    build:
      context: './ambientes_cerrados'
    ports:
      - "9009:80"
    container_name: ambientes_cerrados_gestor
    stdin_open: true
    tty: true
  ambientes_abiertos:
    build:
      context: './ambientes_abiertos'
    ports:
      - "9010:80"
    container_name: ambientes_abiertos_gestor
    stdin_open: true
    tty: true
  deportes:
    build:
      context: './deportes'
    ports:
      - "9011:80"
    container_name: deportes_gestor
    stdin_open: true
    tty: true
  entretenimiento:
    build:
      context: './entretenimiento'
    ports:
      - "9012:80"
    container_name: entretenimiento_gestor
    stdin_open: true
    tty: true
  entretenimiento_familiar:
    build:
      context: './entretenimiento_familiar'
    ports:
      - "9013:80"
    container_name: entretenimiento_familiar_gestor
    stdin_open: true
    tty: true
  entretenimiento_tercera_edad:
    build:
      context: './entretenimiento_tercera_edad'
    ports:
      - "9014:80"
    container_name: entretenimiento_tercera_edad_gestor
    stdin_open: true
    tty: true
  entretenimiento_adulto:
    build:
      context: './entretenimiento_adulto'
    ports:
      - "9015:80"
    container_name: entretenimiento_adulto_gestor
    stdin_open: true
    tty: true
